### ISSUE TITLE
[Bug] Add a check if an internet connection is available when the user clicks on the login button

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#177]

**Comment by colcalex** [comment]
1) Would you like that check to only happen when you sign in, or every time user tries to access backend? 
2) How should the failure of the check be communicated to the user? Could this come with a design guideline?

**Comment by aniri** [comment]
@colcalex hey! and thanks for your help on this app :smiley: 

1. there are only two cases when this check should be made:
* when the user presses the login button
* when the user presses the sync data manually button
It might already be implemented for the second case, so you could use the same approach for the login case as well. 
If it is not yet implemented then:
2. The message should be shown in the simplest method possible, for example a toast message, similar to the android version:
![Screenshot_20191201-194816_Monitorizare Vot](https://user-images.githubusercontent.com/1358055/69917925-4e430b80-1474-11ea-8957-63bbc046bfd8.jpg)

**Comment by CristiHabliuc** [comment]
@colcalex reachability is already implemented in the project. I think @aniri wants a separate message when no internet connection is available on blocking actions instead of using generic timeout error from the OS. These errors should not be displayed when we're saving things locally, only when the user makes a conscious action that would require internet.

Another place I would add is when the section details are sent (the second screen that shows up after the login, when we're actually attaching and validating the section details with the API).

You could add this check directly to the `APIManager` in the appropriate method (login, upload section info) to throw a nicer error immediately when no internet connection is available.

**Comment by colcalex** [comment]
[Pull Request](https://github.com/code4romania/monitorizare-vot-ios/pull/181) closing this issue. However, I did not create a custom view to display message and kept it simple, integrating the error message into the current error handling (display an error message).
